urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import redirect_to
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', redirect_to, {'url': '/chatlogs/post'}),
    url(r'^chatlogs/post/', 'chatlogs.views.post_msg', name='post_msg'),
    url(r'^chatlogs/get/', 'chatlogs.views.get_msg', name='get_msg'),
    url(r'^chatlogs/delete/(?P<path>.*)', 'chatlogs.views.delete_msg', name='delete_msg'),
    url(r'^profile/', 'chatlogs.views.profile', name='profile'),
    url(r'^accounts/profile/', redirect_to, {'url': '/'}),
    url(r'^signup/', 'chatlogs.views.signup', name='signup'),
    url(r'^accounts/login/', 'django.contrib.auth.views.login', name='authentication'),
    url(r'^accounts/logout/', 'chatlogs.views.logout_view', name='logout'),
          

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
#     (r'static/(?P<path>.*)$'), 'django.views.static.serve', {'document_root':settings.STATIC_ROOT}
)

chatlogs/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from datetime import datetime
from django.db.models.fields.related import ForeignKey
from django.contrib.contenttypes import generic
from django.contrib.auth.models import User
from django.conf import settings

DEPARTMENTS= (
        ('Ungrouped','Ungrouped'),
        ('HR','Human Resources'),
        ('BK','Backend Engineers'),
        ('UI','User Interface'),
        ('GR','Graphics Engineers'),
        ('HEN','Hardware Engineers'),
        ('QA','Quality Assurance'),
        ('OTH','Other Dept Guys'),
)

SEX= (
      ('M', 'Male'),
      ('F', 'Female')
)
class Department(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=50)
    def __unicode__(self):
        return u"%s"%self.name
    class Meta:
        db_table = "db_departments"
    
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    department = models.ForeignKey(Department, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    sex_type = models.CharField(max_length=10, choices=SEX, null=True, blank=True)
    class Meta:
        db_table = 'db_user_profiles'
    def __unicode__(self):
        return u"%s"%(self.user)

class Message(models.Model) :
    body = models.TextField(blank=True,null=True)
    user= models.ForeignKey(User)
    created_at = models.DateTimeField(blank=True, default = datetime.now)
    updated_at = models.DateTimeField(default = datetime.now, blank=True)
    is_approved = models.PositiveSmallIntegerField(default = 0)
    members = models.ManyToManyField(User, related_name="messagem2m_set")
    def __unicode__ (self) :
            return u"%s"%(self.title)
    class Meta:
            db_table='db_message'
                

chatlogs/forms.py
from django import forms

class ComposeForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField()
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

chatlogs/views.py
# Create your views here.
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.context_processors import csrf
from chatlogs.models import *


@login_required
def post_msg(request):
    """ Its the home view. Handles the composed message. Returns confirmation. Login is required."""
    data = {}
    limit = request.GET.get('limit', 10)
    start = request.GET.get('start', 0)
    data['messages'] = Message.objects.filter(members = request.user).order_by('-created_at')[start:limit]
    data['departments'] = Department.objects.all()
    if request.method == 'POST':
        data['status'] = ""
        usernames = request.POST.getlist('usernames')
        message = request.POST.get('message')
        if len(usernames)>0:
            if len(message)>0:
                msg_obj = Message(body=message, user=request.user, is_approved=1)
                msg_obj.save()
                msg_obj.members.add(*[int(x) for x in usernames])
                data['status'] = "Your Message is posted Successfully."
            else:
                data['status'] = "Message is missing."
        else:
            data['status'] = "You need to put atleast one receipent before you can post."
        data['body'] = message
    return render_to_response('post_msg.html',{'data':data}, RequestContext(request))

@login_required
def get_msg(request):
    """ Inbox view. Shows all messages sent to user."""
    data = {}
    try:
        limit = int(request.GET.get('limit'))
    except:
        limit = 10
    try:
        start = int(request.GET.get('start'))
    except:
        start = 0
    if request.method == 'POST':
        todelete = request.POST.getlist('todelete')
        for m in todelete:
            Message.objects.get(pk = int(m)).members.remove(request.user)
        data['status'] = "success"
    data['messages'] = Message.objects.filter(members = request.user).order_by('-created_at')[start:limit]
    return render_to_response('get_msg.html',{'data':data}, RequestContext(request))

@login_required
def delete_msg(request, msg_id):
    """ Inbox view. Shows all messages sent to user."""
    data = {}
    data['messages'] = Message.objects.filter(members = request.user)
    return render_to_response('get_msg.html',{'data':data}, RequestContext(request))

@login_required
def profile(request):
    """ Option to change user profile."""
    data = {}
    data['username'] = request.user.username
    data['departments'] = Department.objects.all()
    if request.method == 'POST':
        try:
            cu = UserProfile.objects.get(user=request.user)
        except:
            cu = UserProfile(user=request.user)
        new_department = request.POST.get('department')
        cu.department = Department.objects.get(id=int(new_department))
        cu.save()
        new_password = request.POST.get('password')
        print new_department, new_password
        if(len(new_password)>0):
            u = User.objects.get(pk=request.user.id)
            u.set_password(new_password)
            u.save() 
        data['status'] = "success"

    try:
        data['current_department'] = UserProfile.objects.get(user=request.user).department.id
    except:
        data['current_department'] = ""
    return render_to_response('profile.html',{'data':data}, RequestContext(request))

def logout_view(request):
    """Log users out and re-direct them to the main page."""
    logout(request)
    return HttpResponseRedirect('/')


def signup(request):
    data = {}
    data['departments'] = Department.objects.all()
    if request.method == 'POST':
        username = request.POST.get('username')
        department = request.POST.get('department')
        password = request.POST.get('password')
        password_repeat = request.POST.get('password_repeat')
        if len(username) > 0 and len(password) > 0:
            if password_repeat == password:
                try:
                    user = User.objects.create_user(username, email="", password=password)
                    try:
                        cu = UserProfile(user=user, department_id = department)
                        cu.save()
                        auth_user = authenticate(username=username, password=password)
                        if auth_user is not None:
                            login(request, auth_user)
                        return HttpResponseRedirect('/')
                    except Exception as e:
                        data['status'] = "User Profile not created"
                except:
                    data['status'] = "You're Late, that Username is already taken!"
            else:
                  data['status'] = "Easy, your passwords dont match."
        else:
            data['status'] = "Well, you cant keep your username or password blank, because we cant read your mind (yet)."
    return render_to_response('registration/registration.html', {'data':data}, RequestContext(request))

templates/base.html
{% comment %}
This template is a completely 100% generic HTML5 template.
{% endcomment %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="Prakhar K Goel">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Style (aka, calling Bootstrap) -->
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/bootstrap-responsive.min.css" rel="stylesheet">
    <!-- <link href="{{STATIC_URL}}css/bootstrap-1.1.1.css" rel="stylesheet"> -->

    <!-- Scripts, inc. TableSorter -->
    <script src="http://code.jquery.com/jquery-1.5.2.min.js"></script>
    <!-- <script src="{{STATIC_URL}}js/bootstrap-popover.js"></script> -->
    <!-- <script src="{{STATIC_URL}}js/bootstrap-tooltip.js"></script> -->
    <!-- <script src="{{STATIC_URL}}js/bootstrap.min.js"></script> -->
    
    {% block head %}{% endblock %}
  </head>
  <body>
  	{% block topnav %}{% endblock %}
  	
  	<div class="container">
	{% block content %}{% endblock %}
	{% block footer %}{% endblock %}
	</div>
  </body>
</html>

templates/get_msg.html
{% extends "topnav.html" %}
{% block head %}
    <title>Inbox</title>
<script>
	$(function () {
    $('.checkall').click(function () {
        $(this).parents('tbody:eq(0)').find(':checkbox').attr('checked', this.checked);
    });
});
</script>
{% endblock %}


{% block content %}

<div class="row">
	<div class="span7">
		<p>&nbsp;</p>
		<p>&nbsp;</p>
    	<h2 align="center">Inbox </h2>
		<p>&nbsp;</p>

		{% if data.messages.count > 0 %}
		<form class="form-horizontal" method="POST">
			{% csrf_token %}
		<table class="table table-hover">
			<thead>
			<tr>
				<th>chk</th>
				<th>Id</th>
				<th>Message</th>
				<th>From</th>
				<th>Timestamp</th>
			</tr>
			</thead>
			<tbody>
			{% for m in data.messages %}
			<tr>
                <td>
                	<label class="checkbox">
                    <input type="checkbox" name="todelete" value="{{m.pk}}"/>
                    </label>
                </td>
				<td>{{m.pk}}</td>
				<td>{{m.body}}</td>
				<td>{{m.user.username}}</td>
				<td>{{m.created_at|date:"j/n G:ia"}}</td>
			</tr>
			{% endfor %}
			<tr>
				<td colspan="5">
				<label class="checkbox">
	                <input type="checkbox" class="checkall"/>
	                Select all messages.
	            </label>
	            </td>
			</tr>
			</tbody>
		</table>
		  <div class="control-group">
		    <div class="controls">
		      <button type="submit" class="btn btn-primary">Delete selected Message</button>
		    </div>
		  </div>
		</form>
<br>
<hr />
					
		{% else %}
		<p>&nbsp;</p>
		<p>&nbsp;Your Inbox is empty brother.</p>
		{% endif %}

    </div>
    <div class="span4">
    	<br />
    	<br />
    	<br />
    	<br />
    	<br />
      <h2 align="right">Choose limits</h2>
		<form class="form-horizontal" method="GET">
			{% csrf_token %}
			  <div class="control-group">
			    <label class="control-label" for="id_start">Start from</label>
			    <div class="controls">
			      <input type="text" id="id_start" name="start" placeholder="Most Recent">
			    </div>
			  </div>
			  <div class="control-group">
			    <label class="control-label" for="id_limit">Number of messages</label>
			    <div class="controls">
			      <input type="text" id="id_start" name="limit" placeholder="10">
			    </div>
			  </div>
			  <div class="control-group">
			    <div class="controls">
			      <button type="submit" class="btn btn-primary">Change limits</button>
			    </div>
			  </div>
		</form>
    </div>
    
    
</div>

{% endblock %}

templates/login.html
{% extends "topnav.html" %}
{% block head %}
    <title>Welcome</title>
{% endblock %}

{% block content %}

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1></h1>
        
        <!--<p>Welcome to Multi-Chat</p>
        <p><a class="btn primary large">Learn more &raquo;</a></p>-->
        
      </div>
      
      <!-- Example row of columns -->
      <div class="row">
        <div class="span11">
           <h2 align="center">Login <!-- <small>and Signup</small> --></h2>
<p></p>


<!-- An exemplar signup form -->
{% if wrong_password %}
    <p>Your username and password didn't match, please try again.</p>
{% endif %}

<form action="" method="POST">
	{% csrf_token %}
                <fieldset>
                    <div class="clearfix">
                        <label>Username / Email</label>
                        <div class="input">
                            <input type="text" name="email" />
                        </div>
                    </div>
                    <div class="clearfix">
                        <label>Password</label>
                        <div class="input">
                            <input type="password" name="password" />
                        </div>
                    </div>
                    <div class="clearfix">
                        <div class="input">
                            <ul class="inputs-list">
                                <li>
                                </li>
								<li>
		                            <label>
		                                <input type="checkbox" />
		                                Remember Me
		                            </label>
								</li>
                            </ul>
                        </div>
                    </div>
                    <div class="actions">
                        <button class="btn primary">Go Baby Go</button>
                        <a class="btn">Reset</a>
                    </div>

                </fieldset>
            </form>
<p></p>

        </div>

<!-- The second column -->
        <div class="span5">
          <h2>Signup</h2>
           <p>There is no seperate process for signup. Just key in your email and password.</p>
           <ul>
           	<li>If you are visiting first time, you'll get registered.</li>
           	<li>If you have visited before and entered correct credentials, you'll be logged in.</li>
           	<li>If you have forgotten your password, may God bless you till I create a reset password option.</li>
           </ul>
<!-- <ul class="tabs">
  <li class="active"><a href="#"> </a></li>
  <li><a href="#"></a></li>
  <li><a href="#"></a></li>
</ul> -->
<p></p>
       </div>
      </div>

<!-- Footer -->
      <footer>
        <p>&copy; Company 2011</p>
      </footer>

    </div> <!-- /container -->

{% endblock %}

templates/post_msg.html
{% extends "topnav.html" %}
{% block head %}
    <title>Compose</title>
{% endblock %}


{% block content %}
<script>
	$(function () {
    $('.checkall').click(function () {
        $(this).parents('div:eq(0)').find(':checkbox').attr('checked', this.checked);
    });
});
</script>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span6">
        	<p>&nbsp;</p>
        	<p>&nbsp;</p>
          <h2 align="center">POST Message</h2>
          <p>&nbsp;</p>
			<!-- An exemplar signup form -->

			<form class="form-horizontal" method="POST">
				{% csrf_token %}
				{% if data.status %}
				    <p>{{data.status}}</p>
				{% endif %}
				
				{% for r in data.departments %}
				  <div class="control-group">
				    <label class="control-label">{{r.name}}</label>
				    <div class="controls">
				    {% for u in r.userprofile_set.all %}
		                <label class="checkbox">
		                    <input type="checkbox" name="usernames" value="{{u.user.pk}}"/>
		                    {{u.user.username}}
		                </label>
				    {% endfor %}
		                <label class="checkbox">
		                    <input type="checkbox" class="checkall"/>
		                    Select all in this group.
		                </label>
				    </div>
				  </div>
				{% endfor %}

				  <div class="control-group">
				    <label class="control-label">Message</label>
				    <div class="controls">
		                <textarea rows="5" name="message">{{data.body}}</textarea>
		                <span class="help-block">Type the message here</span>
				    </div>
				  </div>
				  <div class="control-group">
				    <div class="controls">
				      <button type="submit" class="btn btn-primary">Send Message</button>
				    </div>
				  </div>
			</form>
        </div>

        <div class="span4">
        	<p>&nbsp;</p>
        	<p>&nbsp;</p>
          <h2>Your Inbox</h2>
          {% if data.messages.count > 0 %}
			<table class="table table-hover " >
				<thead>
				 <tr>
					<th>Time</th>
					<th>From</th>
					<th>Message</th>
				 </tr>
				</thead>
				<tbody>
				{% for m in data.messages %}
				<tr>
					<td>
						<a href="#" class="" rel="popover" data-content="{{m.body}}" data-original-title="">
							{{m.created_at|date:"j/n"}}
						</a>
					</td>
					<td>{{m.user.username}}</td>
					<td>{{m.body|slice:"30"}}{% if m.body|length > 30 %}...{% endif %}</td>
				</tr>
				{% endfor %}
				</tbody>
			</table>
		  		
		  {% else %}
		  	<p>&nbsp;</p>
			<p>&nbsp;Your Inbox is empty brother.</p>
		  {% endif %}
        
        </div>
      
      </div> <!-- /row -->

{% endblock %}

templates/profile.html
{% extends "topnav.html" %}
{% block head %}
    <title>Edit Profile</title>
{% endblock %}

{% block content %}
      <!-- Example row of columns -->
      <div class="row">
        <div class="span6">

		  <p>&nbsp;</p>
		  <p>&nbsp;</p>
          <h2 align="center">Edit Profile ({{user.username}}) </h2>
          <p>&nbsp;</p>

			<!-- An exemplar signup form -->
			<form class="form-horizontal" method="POST">
			  {% csrf_token %}
				{% if data.status == 'success' %}
				    <p>Your profile is saved successfully.</p>
				{% endif %}

			  <div class="control-group">
			    <label class="control-label" for="id_username">Username</label>
			    <div class="controls">
			      <input type="text" id="id_username" name="username" value="{{data.username}}" readonly="readonly" />
			    </div>
			  </div>
			  <div class="control-group">
			    <label class="control-label" >Department</label>
			    <div class="controls">
	                <select name="department">
	                	{% for r in data.departments %}
	                	{{data.current_department}} {{r.id}}
	                    <option value="{{r.id}}" {% ifequal data.current_department r.id %}selected="selected"{% endifequal %}>{{r.name}}</option>
	                    {% endfor %}
	                </select>
			    </div>
			  </div>
			  <div class="control-group">
			    <label class="control-label" for="id_password">Change Password</label>
			    <div class="controls">
			      <input type="password" id="id_password" name="password" placeholder="Password">
			    </div>
			  </div>
			  <div class="control-group">
			    <div class="controls">
			      <button type="submit" class="btn btn-primary">Save it</button>
			    </div>
			  </div>
			</form>
		</div>
	  </div> <!-- /row -->
{% endblock %}

templates/topnav.html
{% extends "base.html" %}

{% block topnav %}
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="#">Chatlogs</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
                {% if user.is_authenticated %}
                <li class="{% ifequal request.path "/chatlogs/post/" %}active{% endifequal %}"><a href="{% url post_msg %}">Post message</a></li>
                <li class="{% ifequal request.path "/chatlogs/get/" %}active{% endifequal %}"><a href="{% url get_msg %}">Get messages</a></li>
                <li class="{% ifequal request.path "/profile/" %}active{% endifequal %}"><a href="{% url profile %}">Edit Profile</a></li>
                {% else %}
                <li class="{% ifequal request.path "/" %}active{% endifequal %}"><a href="/">Home</a></li>
                <li class="{% ifequal request.path "/signup/" %}active{% endifequal %}"><a href="{% url signup %}">Signup</a></li>
                {% endif %}
              
            </ul>
            {% if user.is_authenticated %}
            <ul class="nav pull-right">
            	<li><a>Welcome {{request.user.username}}</a></li>
            	<li><a href="{% url logout %}">Logout</a></li>
            </ul>
            {% endif %}
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    
{% endblock %}


{% block footer %}
<hr>
<!-- Footer -->
      <footer>
        <p>&copy; Prakhar Goel 2012</p>
      </footer>

{% endblock %}